In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' # don't show all the tensorflow startup messages

import numpy as np
from keras import models
from sys import path
from utils.data_generator import data_generator
from utils.test_utils import get_labels, get_indices, tuple_gen, viewer
from input import Input

In [2]:
# get predictions and convert numerical values to class name
def get_predictions(input, classes, model):
    gen = data_generator(
        f'{path[0]}/processed/{input.dset_name}_test.h5',
        'examples',
        classes,
        shuffle=False
    )

    pred = model.predict(gen, use_multiprocessing=True, workers=8)

    return np.argmax(pred, axis=1), pred

In [3]:
def test(model_name, input, classes):
    model = models.load_model(model_name)

    # predictions represented as integer representation of classes
    best, probs = get_predictions(input, classes, model)


    # labels with class and image number
    labels = get_labels(input)

    indices = get_indices(input)
    


    results = tuple_gen(labels, probs, indices)

    return results

    # viewer(results, classes, 0)

    # def update(index):
    #     viewer(results, classes, index)

    # from ipywidgets import interact, IntSlider

    # interact(update, index=IntSlider(min=0, max=len(results)-1, step=1, value=0))

In [5]:
classes = ['facebook', 'instagram', 'orig', 'telegram', 'twitter',  'whatsapp']
dataset = 'iplab'
epochs = 10
batch_size = 32
architecture = 'dct_cnn_2017'
location = 'dct_models'
h_input = Input(dataset, patch_size=64, sf=[1, 10], his_range=[-50, 50], domain="Histogram")
n_input = Input(dataset, domain="Noise", patch_size=64)
name = f'models/cnn_{architecture}_{h_input.input_shape}_{epochs}_{batch_size}'

results = test(name, h_input, classes)

def update(index):
    viewer(results, classes, index)

from ipywidgets import interact, IntSlider

interact(update, index=IntSlider(min=0, max=len(results)-1, step=1, value=0))

2357/2357 [==============================] - 5s 1ms/step


interactive(children=(IntSlider(value=0, description='index', max=143), Output()), _dom_classes=('widget-inter…

<function __main__.update(index)>

In [24]:
import numpy as np
import os
import matplotlib.pyplot as plt
from jpeg2dct.numpy import loads
from PIL import Image
import io


def hist(dct, sf, his_range):
    sf_num = len(range(*sf))
    # indexes to DC and all AC coefficients
    indexes = [
        (0,0), (0, 1), (1, 0), (2, 0), (1, 1), (0, 2), (0, 3), (1, 2),
        (2, 1), (3, 0), (4, 0), (3, 1), (2, 2),(1, 3), (0, 4), (0, 5),
        (1, 4), (2, 3), (3, 2), (4, 1), (5, 0), (6, 0), (5, 1), (4, 2),
        (3, 3), (2, 4), (1, 5), (0, 6), (0, 7), (1, 6), (2, 5), (3, 4),
        (4, 3), (5, 2), (6, 1), (7, 0), (7, 1), (6, 2), (5, 3), (4, 4),
        (3, 5), (2, 6), (1, 7), (2, 7), (3, 6), (4, 5), (5, 4), (6, 3),
        (7, 2), (7, 3), (6, 4), (5, 5), (4, 6), (3, 7), (4, 7), (5, 6),
        (6, 5), (7, 4), (7, 5), (6, 6), (5, 7), (6, 7), (7, 6), (7, 7)
    ]

    bin_num = len(range(*his_range)) + 1


    coords = indexes[sf[0]: sf[1]]

    # build histogram
    his = np.zeros((sf_num, bin_num))

    c_H = len(dct)
    c_W = len(dct[0])

    # # iterate over each 8x8 block in a patch and build up histogram
    for x in range(c_H):
        for y in range(c_W):
            sf = np.array([dct[x][y].reshape(8,8)[c[0]][c[1]] for c in coords])

            for i, f in enumerate(sf):
                h, _ = np.histogram(f, bins=bin_num, range=his_range)
                his[i] += h # update counts in histogram

    return his.flatten()


def process(patches):
    histograms = []

    for p in patches:
            # extract dct coefficients
            dct, _, _ =  loads(p)
            display(dct)

            # this is just to stop numba complaining 
            his_range = (-50, 50)
            sf = (1, 10)

            # build histograms
            histogram = hist(dct, sf, his_range)
            histograms.append(histogram)
            
    return histograms


fb = f'/home/lazy/snimageclassification/iplab//facebook/CANON_650D_720X480_INDOOR/1.jpg'
wa = f'/home/lazy/snimageclassification/iplab//whatsapp/CANON_650D_720X480_INDOOR/IMG-20160314-WA0011.jpg'
orig = '/home/lazy/snimageclassification/iplab/orig/CANON_650D_720X480_INDOOR/IMG_2635.JPG'

# convert patch to bytes so jpeg2dct can load it
def im_to_bytes(patch, q):
    buf = io.BytesIO()
    patch.save(buf, format='JPEG', qtables=q)
    return buf.getvalue()

def make_patches(image, patch_size, q=None, to_bytes=True):
    patches = []
    p = []
    for i in range(0, image.width-patch_size+1, patch_size):
        for j in range(0, image.height-patch_size+1, patch_size):
            patch = image.crop((i, j, i+patch_size, j+patch_size))
            p.append(patch)
            if to_bytes:
                patch = im_to_bytes(patch, q)

            patches.append(patch)
  
    return patches, p  

image = Image.open(fb)
 # get q tables
qtable = image.quantization

# break down image to patches
patches, p = make_patches(image, 64, qtable, True)

p_h = process(patches)








array([[[ 180,    0,    0, ...,    0,    0,    0],
        [ 189,    0,    0, ...,    0,    0,    0],
        [ 198,    0,    0, ...,    0,    0,    0],
        ...,
        [ 216,    0,    0, ...,    0,    0,    0],
        [ 216,    0,    0, ...,    0,    0,    0],
        [ 225,    0,    0, ...,    0,    0,    0]],

       [[ 207,    0,    0, ...,    0,    0,    0],
        [ 216,    0,    0, ...,    0,    0,    0],
        [ 225,    0,    0, ...,    0,    0,    0],
        ...,
        [ 243,    0,    6, ...,    0,    0,    0],
        [ 252,    0,    0, ...,    0,    0,    0],
        [ 252,    0,    0, ...,    0,    0,    0]],

       [[ 225,    0,    0, ...,    0,    0,    0],
        [ 243,    0,    0, ...,    0,    0,    0],
        [ 243,    0,    0, ...,    0,    0,    0],
        ...,
        [ 270,    0,    0, ...,    0,    0,    0],
        [ 270,    0,    0, ...,    0,    0,    0],
        [ 279,    0,    0, ...,    0,    0,    0]],

       ...,

       [[  27,  -30,    

array([[[-621,    0,    0, ...,    0,    0,    0],
        [-621,    0,    0, ...,    0,    0,    0],
        [-612,    0,    0, ...,    0,    0,    0],
        ...,
        [-612,    0,    0, ...,    0,    0,    0],
        [-603,    0,    0, ...,    0,    0,    0],
        [-603,    0,    0, ...,    0,    0,    0]],

       [[-621,    0,    0, ...,    0,    0,    0],
        [-612,    0,    0, ...,    0,    0,    0],
        [-603,    0,    0, ...,    0,    0,    0],
        ...,
        [-594,    0,    0, ...,    0,    0,    0],
        [-594,    0,    0, ...,    0,    0,    0],
        [-594,    0,    0, ...,    0,    0,    0]],

       [[-621,    0,    0, ...,    0,    0,    0],
        [-621,   -6,    0, ...,    0,    0,    0],
        [-612,    0,    0, ...,    0,    0,    0],
        ...,
        [-603,    0,    0, ...,    0,    0,    0],
        [-603,    0,    0, ...,    0,    0,    0],
        [-603,    0,    0, ...,    0,    0,    0]],

       ...,

       [[-612,    0,    

array([[[-585,    0,    0, ...,    0,    0,    0],
        [-585,    0,    0, ...,    0,    0,    0],
        [-576,    0,    0, ...,    0,    0,    0],
        ...,
        [-567,    0,    0, ...,    0,    0,    0],
        [-558,    0,    0, ...,    0,    0,    0],
        [-558,    0,    0, ...,    0,    0,    0]],

       [[-585,    0,    0, ...,    0,    0,    0],
        [-576,    0,    0, ...,    0,    0,    0],
        [-576,    0,    0, ...,    0,    0,    0],
        ...,
        [-558,    0,    0, ...,    0,    0,    0],
        [-549,    0,    0, ...,    0,    0,    0],
        [-549,    0,    0, ...,    0,    0,    0]],

       [[-576,    0,    0, ...,    0,    0,    0],
        [-567,    0,    0, ...,    0,    0,    0],
        [-567,    0,    0, ...,    0,    0,    0],
        ...,
        [-549,    0,    0, ...,    0,    0,    0],
        [-549,    0,    0, ...,    0,    0,    0],
        [-540,    0,    0, ...,    0,    0,    0]],

       ...,

       [[-558,    0,    

array([[[-567,    0,    0, ...,    0,    0,    0],
        [-558,    0,    0, ...,    0,    0,    0],
        [-549,    0,    0, ...,    0,    0,    0],
        ...,
        [-549,    0,    0, ...,    0,    0,    0],
        [-540,    0,    0, ...,    0,    0,    0],
        [-540,    0,    0, ...,    0,    0,    0]],

       [[-567,    0,    0, ...,    0,    0,    0],
        [-558,    0,    0, ...,    0,    0,    0],
        [-558,    0,    0, ...,    0,    0,    0],
        ...,
        [-549,    0,    0, ...,    0,    0,    0],
        [-540,    0,    0, ...,    0,    0,    0],
        [-540,    0,    0, ...,    0,    0,    0]],

       [[-567,    0,    0, ...,    0,    0,    0],
        [-567,    0,    0, ...,    0,    0,    0],
        [-558,   -6,    0, ...,    0,    0,    0],
        ...,
        [-549,    0,    0, ...,    0,    0,    0],
        [-549,    0,    0, ...,    0,    0,    0],
        [-549,    0,    0, ...,    0,    0,    0]],

       ...,

       [[-585,    0,    

array([[[-585,    0,    0, ...,    0,    0,    0],
        [-585,    0,    0, ...,    0,    0,    0],
        [-576,    0,    0, ...,    0,    0,    0],
        ...,
        [-576,    0,    0, ...,    0,    0,    0],
        [-567,    0,    0, ...,    0,    0,    0],
        [-567,    0,    0, ...,    0,    0,    0]],

       [[-585,    0,    0, ...,    0,    0,    0],
        [-585,    0,    0, ...,    0,    0,    0],
        [-576,    0,    0, ...,    0,    0,    0],
        ...,
        [-567,    0,    0, ...,    0,    0,    0],
        [-567,    0,    0, ...,    0,    0,    0],
        [-567,    0,    0, ...,    0,    0,    0]],

       [[-594,    0,    0, ...,    0,    0,    0],
        [-594,    0,    0, ...,    0,    0,    0],
        [-585,   -6,    0, ...,    0,    0,    0],
        ...,
        [-576,    0,    0, ...,    0,    0,    0],
        [-567,    0,    0, ...,    0,    0,    0],
        [-558,   -6,    0, ...,    0,    0,    0]],

       ...,

       [[-603,    0,    

array([[[-216,  -18,    0, ...,    0,    0,    0],
        [-135,  -24,    0, ...,    0,    0,    0],
        [ -27,  -30,    0, ...,    0,    0,    0],
        ...,
        [ 234,  -18,    0, ...,    0,    0,    0],
        [ 243,    6,    0, ...,    0,    0,    0],
        [ 225,    6,    0, ...,    0,    0,    0]],

       [[ 234,   12,    0, ...,    0,    0,    0],
        [ 198,    0,    0, ...,    0,    0,    0],
        [ 171,    6,    0, ...,    0,    0,    0],
        ...,
        [ 171,    0,    0, ...,    0,    0,    0],
        [ 189,   -6,    0, ...,    0,    0,    0],
        [ 225,  -12,    0, ...,    0,    0,    0]],

       [[ 252,  -18,    0, ...,    0,    0,    0],
        [ 297,   -6,    0, ...,    0,    0,    0],
        [ 315,   -6,    0, ...,    0,    0,    0],
        ...,
        [ 387,   -6,    0, ...,    0,    0,    0],
        [ 414,   -6,    0, ...,    0,    0,    0],
        [ 450,   -6,    0, ...,    0,    0,    0]],

       ...,

       [[ 477,    0,    

array([[[423,   0,   0, ...,   0,   0,   0],
        [432,   0,   0, ...,   0,   0,   0],
        [441,   0,   0, ...,   0,   0,   0],
        ...,
        [477,  -6,   0, ...,   0,   0,   0],
        [486,   0,   0, ...,   0,   0,   0],
        [495,   0,   0, ...,   0,   0,   0]],

       [[441,  -6,   0, ...,   0,   0,   0],
        [450,   0,   0, ...,   0,   0,   0],
        [450,   0,   0, ...,   0,   0,   0],
        ...,
        [468,   0,   0, ...,   0,   0,   0],
        [477,   0,   0, ...,   0,   0,   0],
        [486,   0,   0, ...,   0,   0,   0]],

       [[432,   0,   0, ...,   0,   0,   0],
        [432,   0,   0, ...,   0,   0,   0],
        [441,  -6,   0, ...,   0,   0,   0],
        ...,
        [459,   0,   0, ...,   0,   0,   0],
        [459,   0,   0, ...,   0,   0,   0],
        [468,   0,   0, ...,   0,   0,   0]],

       ...,

       [[369,   0,   6, ...,   0,   0,   0],
        [360,   6,   6, ...,   0,   0,   0],
        [387,  -6,  -6, ...,   0,   0,   0

array([[[ 225,    0,    0, ...,    0,    0,    0],
        [ 234,    0,    0, ...,    0,    0,    0],
        [ 234,    0,    0, ...,    0,    0,    0],
        ...,
        [ 234,    0,    0, ...,    0,    0,    0],
        [ 243,    0,    0, ...,    0,    0,    0],
        [ 243,    0,    0, ...,    0,    0,    0]],

       [[ 261,    0,    0, ...,    0,    0,    0],
        [ 261,    0,    0, ...,    0,    0,    0],
        [ 261,    0,    0, ...,    0,    0,    0],
        ...,
        [ 270,    0,    0, ...,    0,    0,    0],
        [ 270,    0,    0, ...,    0,    0,    0],
        [ 270,    0,    0, ...,    0,    0,    0]],

       [[ 279,    0,    0, ...,    0,    0,    0],
        [ 288,    0,    0, ...,    0,    0,    0],
        [ 288,    0,    0, ...,    0,    0,    0],
        ...,
        [ 297,    0,    0, ...,    0,    0,    0],
        [ 297,    0,    0, ...,    0,    0,    0],
        [ 297,    0,    0, ...,    0,    0,    0]],

       ...,

       [[ 333,   -6,    

array([[[-603,    0,    0, ...,    0,    0,    0],
        [-603,    0,    0, ...,    0,    0,    0],
        [-603,    0,    0, ...,    0,    0,    0],
        ...,
        [-603,    0,    0, ...,    0,    0,    0],
        [-603,    0,    0, ...,    0,    0,    0],
        [-603,    0,    0, ...,    0,    0,    0]],

       [[-594,    0,    0, ...,    0,    0,    0],
        [-585,    0,    0, ...,    0,    0,    0],
        [-594,    0,    0, ...,    0,    0,    0],
        ...,
        [-576,    0,    0, ...,    0,    0,    0],
        [-567,    0,    0, ...,    0,    0,    0],
        [-567,    0,    0, ...,    0,    0,    0]],

       [[-594,    0,    0, ...,    0,    0,    0],
        [-594,    0,    0, ...,    0,    0,    0],
        [-585,    0,    0, ...,    0,    0,    0],
        ...,
        [-576,    0,    0, ...,    0,    0,    0],
        [-567,    0,    0, ...,    0,    0,    0],
        [-567,    0,    0, ...,    0,    0,    0]],

       ...,

       [[-585,    0,    

array([[[-522,  -42,   36, ...,    0,    0,    0],
        [-423,   -6,   -6, ...,    0,    0,    0],
        [-387,   42,   36, ...,    0,    0,    0],
        ...,
        [-378,   -6,    0, ...,    0,    0,    0],
        [-387,   18,    0, ...,    0,    0,    0],
        [-468,   30,    0, ...,    0,    0,    0]],

       [[-468, -108,   96, ...,    0,    0,    0],
        [-378,  -30,  -18, ...,    0,    0,    0],
        [-243,   48,   66, ...,    0,    0,    0],
        ...,
        [-342,  -96,  108, ...,    0,    0,    0],
        [-441,  -36,    6, ...,    0,    0,    0],
        [-360,   36,  -78, ...,    0,    0,    0]],

       [[-459,  -90,   60, ...,    0,    0,    0],
        [-351,  -24,  -18, ...,    0,    0,    0],
        [-261,   60,   42, ...,    0,    0,    0],
        ...,
        [-279, -102,   84, ...,    0,    0,    0],
        [-306,  -18,  -18, ...,    0,    0,    0],
        [-360,   48,  -60, ...,    0,    0,    0]],

       ...,

       [[-387, -120,   -

array([[[-531,    0,    0, ...,    0,    0,    0],
        [-531,    0,    0, ...,    0,    0,    0],
        [-522,  -12,    6, ...,    0,    0,    0],
        ...,
        [-387,   12,    0, ...,    0,    0,    0],
        [-414,    0,    0, ...,    0,    0,    0],
        [-414,   18,  -12, ...,    0,    0,    0]],

       [[-540,    0,    0, ...,    0,    0,    0],
        [-540,    0,    0, ...,    0,    0,    0],
        [-441,  -90,    6, ...,    0,    0,    0],
        ...,
        [-279,   78,  -42, ...,    0,    0,    0],
        [-333,  -42,    0, ...,    0,    0,    0],
        [-324,  -42,  -42, ...,    0,    0,    0]],

       [[-540,    0,    0, ...,    0,    0,    0],
        [-540,    0,    0, ...,    0,    0,    0],
        [-513,  -24,    6, ...,    0,    0,    0],
        ...,
        [-459,    0,    0, ...,    0,    0,    0],
        [-459,    6,    0, ...,    0,    0,    0],
        [-468,   -6,   -6, ...,    0,    0,    0]],

       ...,

       [[-558,    0,    

array([[[-567,    0,    0, ...,    0,    0,    0],
        [-549,    0,    0, ...,    0,    0,    0],
        [-540,   -6,    0, ...,    0,    0,    0],
        ...,
        [-549,    0,    0, ...,    0,    0,    0],
        [-549,    0,    0, ...,    0,    0,    0],
        [-549,    0,    0, ...,    0,    0,    0]],

       [[-558,    0,    0, ...,    0,    0,    0],
        [-558,    0,    0, ...,    0,    0,    0],
        [-549,    0,    0, ...,    0,    0,    0],
        ...,
        [-549,    0,    0, ...,    0,    0,    0],
        [-549,    0,    0, ...,    0,    0,    0],
        [-540,    0,    0, ...,    0,    0,    0]],

       [[-549,    0,    0, ...,    0,    0,    0],
        [-549,    0,    0, ...,    0,    0,    0],
        [-549,    0,    0, ...,    0,    0,    0],
        ...,
        [-549,    0,    0, ...,    0,    0,    0],
        [-540,    0,    0, ...,    0,    0,    0],
        [-540,    0,    0, ...,    0,    0,    0]],

       ...,

       [[-567,    0,    

array([[[189,  12,   0, ...,   0,   0,   0],
        [162,   0,   6, ...,   0,   0,   0],
        [162,   0,   0, ...,   0,   0,   0],
        ...,
        [180,  -6,   0, ...,   0,   0,   0],
        [198,  -6,   0, ...,   0,   0,   0],
        [234, -12,   0, ...,   0,   0,   0]],

       [[279, -18,   0, ...,   0,   0,   0],
        [333, -12,  -6, ...,   0,   0,   0],
        [360,  -6,   0, ...,   0,   0,   0],
        ...,
        [432,  -6,   0, ...,   0,   0,   0],
        [459,  -6,   0, ...,   0,   0,   0],
        [477,  -6,   0, ...,   0,   0,   0]],

       [[468,  -6,   0, ...,   0,   0,   0],
        [495,  -6,   0, ...,   0,   0,   0],
        [522,  -6,   0, ...,   0,   0,   0],
        ...,
        [549,   0,   0, ...,   0,   0,   0],
        [558,   0,   0, ...,   0,   0,   0],
        [558,   0,   0, ...,   0,   0,   0]],

       ...,

       [[513,   0,   0, ...,   0,   0,   0],
        [522,   0,   0, ...,   0,   0,   0],
        [522,   0,   0, ...,   0,   0,   0

array([[[495,   0,   0, ...,   0,   0,   0],
        [495,   0,   0, ...,   0,   0,   0],
        [504,   0,   0, ...,   0,   0,   0],
        ...,
        [504,   0,   0, ...,   0,   0,   0],
        [504,   6,  -6, ...,   0,   0,   0],
        [495, -18, -12, ...,   0,   0,   0]],

       [[495,   0,   0, ...,   0,   0,   0],
        [495,   0,   0, ...,   0,   0,   0],
        [477, -12,  12, ...,   0,   0,   0],
        ...,
        [486,   6, -12, ...,   0,   0,   0],
        [468,   6, -24, ...,   0,   0,   0],
        [495, -12,  -6, ...,   0,   0,   0]],

       [[468,  -6,  12, ...,   0,   0,   0],
        [477,   0,   0, ...,   0,   0,   0],
        [459,   6,   6, ...,   0,   0,   0],
        ...,
        [477,   0,   0, ...,   0,   0,   0],
        [459,   0,   0, ...,   0,   0,   0],
        [468,  -6,   6, ...,   0,   0,   0]],

       ...,

       [[396,   0, -12, ...,   0,   0,   0],
        [414, -12,   6, ...,   0,   0,   0],
        [450,  -6,   6, ...,   0,   0,   0

array([[[ 243,    0,    0, ...,    0,    0,    0],
        [ 243,    0,    0, ...,    0,    0,    0],
        [ 234,    0,    0, ...,    0,    0,    0],
        ...,
        [ 225,    0,    0, ...,    0,    0,    0],
        [ 153,   84,  -60, ...,    0,    0,    0],
        [-252,   60,  -18, ...,    0,    0,    0]],

       [[ 270,    0,    0, ...,    0,    0,    0],
        [ 270,    0,    0, ...,    0,    0,    0],
        [ 261,    0,    0, ...,    0,    0,    0],
        ...,
        [ 243,    0,    0, ...,    0,    0,    0],
        [ 243,    0,    0, ...,    0,    0,    0],
        [ 234,    6,    0, ...,    0,    0,    0]],

       [[ 297,    0,    0, ...,    0,    0,    0],
        [ 297,    0,    0, ...,    0,    0,    0],
        [ 297,    0,    0, ...,    0,    0,    0],
        ...,
        [ 279,    0,    0, ...,    0,    0,    0],
        [ 270,    0,    6, ...,    0,    0,    0],
        [ 270,    0,    0, ...,    0,    0,    0]],

       ...,

       [[ 369,    0,    

array([[[-603,    0,    0, ...,    0,    0,    0],
        [-594,   -6,    0, ...,    0,    0,    0],
        [-549,  -18,    0, ...,    0,    0,    0],
        ...,
        [-270,  -30,    0, ...,    0,    0,    0],
        [-144,  -42,    0, ...,    0,    0,    0],
        [  -9,  -42,    0, ...,    0,    0,    0]],

       [[-567,    0,    0, ...,    0,    0,    0],
        [-567,    0,    0, ...,    0,    0,    0],
        [-567,    0,    0, ...,    0,    0,    0],
        ...,
        [-585,    0,    0, ...,    0,    0,    0],
        [-576,    0,    0, ...,    0,    0,    0],
        [-585,    0,    0, ...,    0,    0,    0]],

       [[-567,    0,    0, ...,    0,    0,    0],
        [-558,    0,    0, ...,    0,    0,    0],
        [-558,    0,    0, ...,    0,    0,    0],
        ...,
        [-549,    0,    0, ...,    0,    0,    0],
        [-549,    0,    0, ...,    0,    0,    0],
        [-549,    0,    0, ...,    0,    0,    0]],

       ...,

       [[-549,   -6,    

array([[[-504,    0,    0, ...,    0,    0,    0],
        [-495,    0,    0, ...,    0,    0,    0],
        [-495,    0,    0, ...,    0,    0,    0],
        ...,
        [-477,    0,    0, ...,    0,    0,    0],
        [-468,    0,    0, ...,    0,    0,    0],
        [-468,    0,    0, ...,    0,    0,    0]],

       [[-495,    0,    0, ...,    0,    0,    0],
        [-495,    0,    0, ...,    0,    0,    0],
        [-486,    0,    0, ...,    0,    0,    0],
        ...,
        [-477,    0,    0, ...,    0,    0,    0],
        [-468,    0,    0, ...,    0,    0,    0],
        [-459,    0,    0, ...,    0,    0,    0]],

       [[-495,    0,    0, ...,    0,    0,    0],
        [-486,    0,    0, ...,    0,    0,    0],
        [-441,  -54,   42, ...,    0,    0,    0],
        ...,
        [-468,    0,    0, ...,    0,    0,    0],
        [-468,    0,    0, ...,    0,    0,    0],
        [-459,    0,    0, ...,    0,    0,    0]],

       ...,

       [[-504,    0,    

array([[[-468,   30,  -12, ...,    0,    0,    0],
        [-522,    0,    0, ...,    0,    0,    0],
        [-522,    0,    0, ...,    0,    0,    0],
        ...,
        [-522,    0,    0, ...,    0,    0,    0],
        [-522,    0,    0, ...,    0,    0,    0],
        [-486,   12,  -42, ...,    0,    0,    0]],

       [[-423,   84,   30, ...,    0,    0,    0],
        [-531,    0,    0, ...,    0,    0,    0],
        [-531,    0,    0, ...,    0,    0,    0],
        ...,
        [-531,    0,    0, ...,    0,    0,    0],
        [-531,  -12,    6, ...,    0,    0,    0],
        [-495,   12,   -6, ...,    0,    0,    0]],

       [[-513,   12,    6, ...,    0,    0,    0],
        [-531,    0,    0, ...,    0,    0,    0],
        [-531,    0,    0, ...,    0,    0,    0],
        ...,
        [-504,  -30,   30, ...,    0,    0,    0],
        [-504,   12,   30, ...,    0,    0,    0],
        [-468,  -18,   -6, ...,    0,    0,    0]],

       ...,

       [[-216,  -36,   -

array([[[-549,    0,    0, ...,    0,    0,    0],
        [-549,    0,    0, ...,    0,    0,    0],
        [-549,    0,    0, ...,    0,    0,    0],
        ...,
        [-549,    0,    0, ...,    0,    0,    0],
        [-558,    0,    0, ...,    0,    0,    0],
        [-549,    0,    0, ...,    0,    0,    0]],

       [[-549,    0,    0, ...,    0,    0,    0],
        [-549,    0,    0, ...,    0,    0,    0],
        [-549,    0,    0, ...,    0,    0,    0],
        ...,
        [-549,    6,    0, ...,    0,    0,    0],
        [-558,    0,    0, ...,    0,    0,    0],
        [-558,    0,    0, ...,    0,    0,    0]],

       [[-540,    0,    0, ...,    0,    0,    0],
        [-540,    0,    0, ...,    0,    0,    0],
        [-540,    0,    0, ...,    0,    0,    0],
        ...,
        [-549,    0,    0, ...,    0,    0,    0],
        [-549,    0,    0, ...,    0,    0,    0],
        [-549,    0,    0, ...,    0,    0,    0]],

       ...,

       [[-558,    0,    

array([[[279, -12,   0, ...,   0,   0,   0],
        [342, -18,   0, ...,   0,   0,   0],
        [378,  -6,   0, ...,   0,   0,   0],
        ...,
        [441,  -6,   0, ...,   0,   0,   0],
        [459,  -6,   0, ...,   0,   0,   0],
        [477,   0,   0, ...,   0,   0,   0]],

       [[504,  -6,   0, ...,   0,   0,   0],
        [531,  -6,   0, ...,   0,   0,   0],
        [549,  -6,   0, ...,   0,   0,   0],
        ...,
        [558,   0,   0, ...,   0,   0,   0],
        [558,   0,   0, ...,   0,   0,   0],
        [558,   0,   0, ...,   0,   0,   0]],

       [[558,   0,   0, ...,   0,   0,   0],
        [558,   0,   0, ...,   0,   0,   0],
        [558,   0,   0, ...,   0,   0,   0],
        ...,
        [549,   0,   0, ...,   0,   0,   0],
        [549,   0,   0, ...,   0,   0,   0],
        [549,   0,   0, ...,   0,   0,   0]],

       ...,

       [[513,   0,   0, ...,   0,   0,   0],
        [504,   0,   0, ...,   0,   0,   0],
        [504,   0,   0, ...,   0,   0,   0

array([[[ 513,    0,    0, ...,    0,    0,    0],
        [ 513,    6,    0, ...,    0,    0,    0],
        [ 513,    0,    0, ...,    0,    0,    0],
        ...,
        [ 504,    6,    0, ...,    0,    0,    0],
        [ 504,    6,    0, ...,    0,    0,    0],
        [ 504,    0,    0, ...,    0,    0,    0]],

       [[ 504,    0,    0, ...,    0,    0,    0],
        [ 495,  -12,  -12, ...,    0,    0,    0],
        [ 495,    0,    0, ...,    0,    0,    0],
        ...,
        [ 468,   -6,   18, ...,    0,    0,    0],
        [ 477,    6,    6, ...,    0,    0,    0],
        [ 477,    0,    6, ...,    0,    0,    0]],

       [[ 486,   -6,    0, ...,    0,    0,    0],
        [ 477,   18,    0, ...,    0,    0,    0],
        [ 486,   -6,    0, ...,    0,    0,    0],
        ...,
        [ 432,  -12,   18, ...,    0,    0,    0],
        [ 468,    0,   18, ...,    0,    0,    0],
        [ 477,  -12,   12, ...,    0,    0,    0]],

       ...,

       [[ 477,  -12,    

array([[[-162, -210,   60, ...,    0,    0,    0],
        [ 207,    0,    0, ...,    0,    0,    0],
        [ 171,  -12,   18, ...,    0,    0,    0],
        ...,
        [  54,   24,   -6, ...,    0,    0,    0],
        [ -27,   12,    0, ...,    0,    0,    0],
        [ -45,    0,    6, ...,    0,    0,    0]],

       [[ 234,    0,    0, ...,    0,    0,    0],
        [ 234,    0,    0, ...,    0,    0,    0],
        [ 225,    6,    0, ...,    0,    0,    0],
        ...,
        [ 207,    0,    0, ...,    0,    0,    0],
        [ 207,    0,    0, ...,    0,    0,    0],
        [ 189,   12,    0, ...,    0,    0,    0]],

       [[ 270,    0,    0, ...,    0,    0,    0],
        [ 261,    0,    0, ...,    0,    0,    0],
        [ 234,   -6,    6, ...,    0,    0,    0],
        ...,
        [ 234,    0,    0, ...,    0,    0,    0],
        [ 234,    0,    0, ...,    0,    0,    0],
        [ 225,    0,    0, ...,    0,    0,    0]],

       ...,

       [[ 351,    0,    

array([[[ 144,  -36,   -6, ...,    0,    0,    0],
        [ 243,  -18,    0, ...,    0,    0,    0],
        [ 297,  -12,    0, ...,    0,    0,    0],
        ...,
        [ 369,    0,    0, ...,    0,    0,    0],
        [ 369,    0,    0, ...,    0,    0,    0],
        [ 360,    0,    0, ...,    0,    0,    0]],

       [[-585,   -6,    0, ...,    0,    0,    0],
        [-558,  -18,    6, ...,    0,    0,    0],
        [-459,  -24,    0, ...,    0,    0,    0],
        ...,
        [-117,  -42,    0, ...,    0,    0,    0],
        [  27,  -42,    0, ...,    0,    0,    0],
        [ 171,  -36,    0, ...,    0,    0,    0]],

       [[-558,    0,    0, ...,    0,    0,    0],
        [-567,    0,    0, ...,    0,    0,    0],
        [-558,    0,    0, ...,    0,    0,    0],
        ...,
        [-567,    0,    0, ...,    0,    0,    0],
        [-558,    0,    0, ...,    0,    0,    0],
        [-558,    0,    0, ...,    0,    0,    0]],

       ...,

       [[-495,    0,    

array([[[-459,    0,    0, ...,    0,    0,    0],
        [-450,    0,    0, ...,    0,    0,    0],
        [-441,    0,    0, ...,    0,    0,    0],
        ...,
        [-432,   -6,    6, ...,    0,    0,    0],
        [-423,    0,    0, ...,    0,    0,    0],
        [-414,    0,    0, ...,    0,    0,    0]],

       [[-459,    0,    0, ...,    0,    0,    0],
        [-450,    0,    0, ...,    0,    0,    0],
        [-441,    0,    0, ...,    0,    0,    0],
        ...,
        [-432,   -6,    0, ...,    0,    0,    0],
        [-432,    0,    0, ...,    0,    0,    0],
        [-423,    0,    0, ...,    0,    0,    0]],

       [[-450,    0,    0, ...,    0,    0,    0],
        [-450,    0,    0, ...,    0,    0,    0],
        [-450,    0,    0, ...,    0,    0,    0],
        ...,
        [-450,    0,    0, ...,    0,    0,    0],
        [-450,    0,    0, ...,    0,    0,    0],
        [-450,    0,    0, ...,    0,    0,    0]],

       ...,

       [[-495,    0,    

array([[[-513,   -6,    0, ...,    0,    0,    0],
        [-423,  -12,    0, ...,    0,    0,    0],
        [-423,    0,    0, ...,    0,    0,    0],
        ...,
        [-504,    6,   36, ...,    0,    0,    0],
        [-504,  -42,   36, ...,    0,    0,    0],
        [-477,  -36,   48, ...,    0,    0,    0]],

       [[-531,    0,    0, ...,    0,    0,    0],
        [-531,    0,    0, ...,    0,    0,    0],
        [-540,    0,    0, ...,    0,    0,    0],
        ...,
        [-549,    6,    0, ...,    0,    0,    0],
        [-549,    0,    0, ...,    0,    0,    0],
        [-522,   24,  -18, ...,    0,    0,    0]],

       [[-432,    0,    0, ...,    0,    0,    0],
        [-432,    6,   -6, ...,   58,    0,    0],
        [-540,    0,    0, ...,    0,    0,    0],
        ...,
        [-549,    6,    0, ...,    0,    0,    0],
        [-558,    0,    0, ...,    0,    0,    0],
        [-468,   30,  -66, ...,    0,    0,    0]],

       ...,

       [[-477,  -12,  -7

array([[[-549,    0,    0, ...,    0,    0,    0],
        [-549,    0,    0, ...,    0,    0,    0],
        [-558,    0,    0, ...,    0,    0,    0],
        ...,
        [-558,    0,    0, ...,    0,    0,    0],
        [-567,    6,    0, ...,    0,    0,    0],
        [-576,    0,    0, ...,    0,    0,    0]],

       [[-549,    0,    0, ...,    0,    0,    0],
        [-549,    0,    0, ...,    0,    0,    0],
        [-558,    6,    0, ...,    0,    0,    0],
        ...,
        [-558,    6,    0, ...,    0,    0,    0],
        [-576,    0,    0, ...,    0,    0,    0],
        [-576,    0,    0, ...,    0,    0,    0]],

       [[-549,    0,    0, ...,    0,    0,    0],
        [-558,    0,    0, ...,    0,    0,    0],
        [-558,    0,    0, ...,    0,    0,    0],
        ...,
        [-576,    0,    6, ...,    0,    0,    0],
        [-576,    0,    0, ...,    0,    0,    0],
        [-585,    0,    0, ...,    0,    0,    0]],

       ...,

       [[-513,  -18,    

array([[[495,  -6,   0, ...,   0,   0,   0],
        [513,  -6,   0, ...,   0,   0,   0],
        [522,   0,   0, ...,   0,   0,   0],
        ...,
        [522,   0,   0, ...,   0,   0,   0],
        [513,   0,   0, ...,   0,   0,   0],
        [504,   0,   0, ...,   0,   0,   0]],

       [[549,   0,   0, ...,   0,   0,   0],
        [540,   0,   0, ...,   0,   0,   0],
        [540,   0,   0, ...,   0,   0,   0],
        ...,
        [531,   0,   0, ...,   0,   0,   0],
        [522,   0,   0, ...,   0,   0,   0],
        [504,   6,   0, ...,   0,   0,   0]],

       [[549,   0,   0, ...,   0,   0,   0],
        [540,   0,   0, ...,   0,   0,   0],
        [540,   0,   0, ...,   0,   0,   0],
        ...,
        [522,   0,   0, ...,   0,   0,   0],
        [513,   6,   0, ...,   0,   0,   0],
        [495,   6,   0, ...,   0,   0,   0]],

       ...,

       [[531,   0,   0, ...,   0,   0,   0],
        [531,   0,   0, ...,   0,   0,   0],
        [522,   0,   0, ...,   0,   0,   0

array([[[ 504,   -6,    0, ...,    0,    0,    0],
        [ 504,    0,    0, ...,    0,    0,    0],
        [ 495,    0,    0, ...,    0,    0,    0],
        ...,
        [ 405,   48,  -18, ...,    0,    0,    0],
        [ 423,    0,   12, ...,    0,    0,    0],
        [ 423,    6,    0, ...,    0,    0,    0]],

       [[ 495,  -12,    0, ...,    0,    0,    0],
        [ 504,    6,    0, ...,    0,    0,    0],
        [ 495,    0,    0, ...,    0,    0,    0],
        ...,
        [ 423,    6,    0, ...,    0,    0,    0],
        [ 414,  -12,   12, ...,    0,    0,    0],
        [ 432,   12,    0, ...,    0,    0,    0]],

       [[ 522,  -18,    6, ...,    0,    0,    0],
        [ 522,   18,    0, ...,    0,    0,    0],
        [ 486,    0,    0, ...,    0,    0,    0],
        ...,
        [ 414,   18,   -6, ...,    0,    0,    0],
        [ 378,  -30,   18, ...,    0,    0,    0],
        [ 423,   12,   -6, ...,    0,    0,    0]],

       ...,

       [[ 297,  108,    

array([[[-36,  -6,   6, ...,   0,   0,   0],
        [ -9,   0,   0, ...,   0,   0,   0],
        [-18,   0,   0, ...,   0,   0,   0],
        ...,
        [-27,   0,   0, ...,   0,   0,   0],
        [-36,   0,   0, ...,   0,   0,   0],
        [-45,   0,   0, ...,   0,   0,   0]],

       [[135,  18,   0, ...,   0,   0,   0],
        [ 90,  12,   0, ...,   0,   0,   0],
        [ 54,  12,   0, ...,   0,   0,   0],
        ...,
        [ -9,   0,   0, ...,   0,   0,   0],
        [-18,   6,   0, ...,   0,   0,   0],
        [-27,   0,   0, ...,   0,   0,   0]],

       [[216,   0,   0, ...,   0,   0,   0],
        [216,   6,   0, ...,   0,   0,   0],
        [207,   0,   0, ...,   0,   0,   0],
        ...,
        [117,  18,   0, ...,   0,   0,   0],
        [ 36,  30,   0, ...,   0,   0,   0],
        [-36,  12,   6, ...,   0,   0,   0]],

       ...,

       [[297,   0,   0, ...,   0,   0,   0],
        [288,   6,   0, ...,   0,   0,   0],
        [279,   0,   0, ...,   0,   0,   0

array([[[ 360,    0,    0, ...,    0,    0,    0],
        [ 351,    0,    0, ...,    0,    0,    0],
        [ 342,    0,    0, ...,    0,    0,    0],
        ...,
        [ 324,    0,    0, ...,    0,    0,    0],
        [ 315,    6,    0, ...,    0,    0,    0],
        [ 306,    0,    0, ...,    0,    0,    0]],

       [[ 297,  -24,   -6, ...,    0,    0,    0],
        [ 333,   -6,    0, ...,    0,    0,    0],
        [ 351,    0,    0, ...,    0,    0,    0],
        ...,
        [ 342,    6,    0, ...,    0,    0,    0],
        [ 333,    6,    0, ...,    0,    0,    0],
        [ 324,    0,    0, ...,    0,    0,    0]],

       [[-540,  -12,    6, ...,    0,    0,    0],
        [-441,  -36,    0, ...,    0,    0,    0],
        [-315,  -36,    0, ...,    0,    0,    0],
        ...,
        [  99,  -36,    0, ...,    0,    0,    0],
        [ 234,  -42,    0, ...,    0,    0,    0],
        [ 360,  -30,   -6, ...,    0,    0,    0]],

       ...,

       [[-441,   -6,    

array([[[-414,    0,    0, ...,    0,    0,    0],
        [-405,    0,    0, ...,    0,    0,    0],
        [-405,    0,    0, ...,    0,    0,    0],
        ...,
        [-405,    0,    0, ...,    0,    0,    0],
        [-414,    0,    0, ...,    0,    0,    0],
        [-432,    6,    0, ...,    0,    0,    0]],

       [[-423,    0,    0, ...,    0,    0,    0],
        [-423,    0,    0, ...,    0,    0,    0],
        [-423,    0,    0, ...,    0,    0,    0],
        ...,
        [-441,    0,    0, ...,    0,    0,    0],
        [-450,    0,    0, ...,    0,    0,    0],
        [-477,    6,    0, ...,    0,    0,    0]],

       [[-450,    0,    0, ...,    0,    0,    0],
        [-450,    0,    0, ...,    0,    0,    0],
        [-459,    0,    0, ...,    0,    0,    0],
        ...,
        [-486,    6,    0, ...,    0,    0,    0],
        [-504,    6,    0, ...,    0,    0,    0],
        [-522,    6,    0, ...,    0,    0,    0]],

       ...,

       [[-522,    0,    

array([[[-504,   60,   48, ...,    0,    0,    0],
        [-540,   18,    0, ...,    0,    0,    0],
        [-558,    0,    0, ...,    0,    0,    0],
        ...,
        [-585,    0,    0, ...,    0,    0,    0],
        [-576,    0,    0, ...,    0,    0,    0],
        [-576,    6,    0, ...,    0,    0,    0]],

       [[-558,    0,    0, ...,    0,    0,    0],
        [-558,    6,    0, ...,    0,    0,    0],
        [-567,    0,    0, ...,    0,    0,    0],
        ...,
        [-594,    0,    0, ...,    0,    0,    0],
        [-603,    0,    0, ...,    0,    0,    0],
        [-603,    0,    0, ...,    0,    0,    0]],

       [[-558,    0,    0, ...,    0,    0,    0],
        [-567,    0,    0, ...,    0,    0,    0],
        [-576,    0,    0, ...,    0,    0,    0],
        ...,
        [-594,    6,    0, ...,    0,    0,    0],
        [-603,    0,    0, ...,    0,    0,    0],
        [-603,    0,    0, ...,    0,    0,    0]],

       ...,

       [[-576,    6,    

array([[[-585,    0,    0, ...,    0,    0,    0],
        [-594,    6,    0, ...,    0,    0,    0],
        [-603,    0,    0, ...,    0,    0,    0],
        ...,
        [-621,    0,    0, ...,    0,    0,    0],
        [-630,    0,    0, ...,    0,    0,    0],
        [-639,    0,    6, ...,    0,    0,    0]],

       [[-585,    0,    0, ...,    0,    0,    0],
        [-594,    6,    0, ...,    0,    0,    0],
        [-603,    0,    0, ...,    0,    0,    0],
        ...,
        [-630,    6,    0, ...,    0,    0,    0],
        [-648,    0,    0, ...,    0,    0,    0],
        [-648,    0,    0, ...,    0,    0,    0]],

       [[-594,    6,    0, ...,    0,    0,    0],
        [-612,    6,    0, ...,    0,    0,    0],
        [-621,    6,    0, ...,    0,    0,    0],
        ...,
        [-657,    6,    0, ...,    0,    0,    0],
        [-666,    6,    0, ...,    0,    0,    0],
        [-675,    0,    0, ...,    0,    0,    0]],

       ...,

       [[  18,  -18,    

array([[[495,   0,   0, ...,   0,   0,   0],
        [486,   0,   0, ...,   0,   0,   0],
        [477,   0,   0, ...,   0,   0,   0],
        ...,
        [531,  12,  24, ...,   0,   0,   0],
        [513,   6,   0, ...,   0,   0,   0],
        [504,   0,   0, ...,   0,   0,   0]],

       [[495,   6,   0, ...,   0,   0,   0],
        [486,   0,   0, ...,   0,   0,   0],
        [486,   0,   0, ...,   0,   0,   0],
        ...,
        [531,  24,  30, ...,   0,   0,   0],
        [513,   6,   0, ...,   0,   0,   0],
        [513,   0,   0, ...,   0,   0,   0]],

       [[486,   0,   0, ...,   0,   0,   0],
        [468,   6,   0, ...,   0,   0,   0],
        [459,   0,   0, ...,   0,   0,   0],
        ...,
        [531,  30,  30, ...,   0,   0,   0],
        [513,   6,   0, ...,   0,   0,   0],
        [504,   0,   6, ...,   0,   0,   0]],

       ...,

       [[468,   0,   0, ...,   0,   0,   0],
        [459,   0,   6, ...,   0,   0,   0],
        [459,   0,   0, ...,   0,   0,   0

array([[[ 387,    6,   18, ...,    0,    0,    0],
        [ 387,    0,    0, ...,    0,    0,    0],
        [ 414,   -6,  -12, ...,    0,    0,    0],
        ...,
        [ 513,   54,   -6, ...,    0,    0,    0],
        [ 468,    6,    0, ...,    0,    0,    0],
        [ 450,   36,  -48, ...,    0,    0,    0]],

       [[ 387,   30,   -6, ...,    0,    0,    0],
        [ 378,  -12,  -12, ...,    0,    0,    0],
        [ 459,  -36,    6, ...,    0,    0,    0],
        ...,
        [ 513,   54,  -12, ...,    0,    0,    0],
        [ 459,    6,    0, ...,    0,    0,    0],
        [ 423,   48,  -48, ...,    0,    0,    0]],

       [[ 387,    6,    0, ...,    0,    0,    0],
        [ 441,  -42,   -6, ...,    0,    0,    0],
        [ 531,   -6,   -6, ...,    0,    0,    0],
        ...,
        [ 513,   54,  -18, ...,    0,    0,    0],
        [ 441,    6,    0, ...,    0,    0,    0],
        [ 387,   78,  -54, ...,    0,    0,    0]],

       ...,

       [[-459,    0,    

array([[[-45,   0,   0, ...,   0,   0,   0],
        [-54,   0,   0, ...,   0,   0,   0],
        [-54,   0,   0, ...,   0,   0,   0],
        ...,
        [-36,   0,   0, ...,   0,   0,   0],
        [-36,   0,   0, ...,   0,   0,   0],
        [-36,   0,   0, ...,   0,   0,   0]],

       [[-27,   0,   0, ...,   0,   0,   0],
        [-27,   0,   0, ...,   0,   0,   0],
        [-45,   0,   0, ...,   0,   0,   0],
        ...,
        [-45,   0,   0, ...,   0,   0,   0],
        [-45,   0,   0, ...,   0,   0,   0],
        [-54,   0,   0, ...,   0,   0,   0]],

       [[-54,  -6,   6, ...,   0,   0,   0],
        [-36,   0,   0, ...,   0,   0,   0],
        [-27,   0,   0, ...,   0,   0,   0],
        ...,
        [-45,   0,   0, ...,   0,   0,   0],
        [-54,   6,   0, ...,   0,   0,   0],
        [-63,   0,   0, ...,   0,   0,   0]],

       ...,

       [[216,   6,   0, ...,   0,   0,   0],
        [198,   6,   0, ...,   0,   0,   0],
        [189,   6,   0, ...,   0,   0,   0

array([[[ 288,    6,    0, ...,    0,    0,    0],
        [ 261,    6,    0, ...,    0,    0,    0],
        [ 252,    0,    0, ...,    0,    0,    0],
        ...,
        [ 207,   -6,    0, ...,    0,    0,    0],
        [ 234,   -6,  -12, ...,    0,    0,    0],
        [ 225,    0,    0, ...,    0,    0,    0]],

       [[ 306,    6,    0, ...,    0,    0,    0],
        [ 288,    6,    0, ...,    0,    0,    0],
        [ 270,    6,    0, ...,    0,    0,    0],
        ...,
        [ 225,    0,    0, ...,    0,    0,    0],
        [ 261,   -6,  -12, ...,    0,    0,    0],
        [ 252,    0,    0, ...,    0,    0,    0]],

       [[ 387,   12,   -6, ...,    0,    0,    0],
        [ 333,   12,    0, ...,    0,    0,    0],
        [ 288,   12,    0, ...,    0,    0,    0],
        ...,
        [ 243,   -6,    0, ...,    0,    0,    0],
        [ 279,    0,  -18, ...,    0,    0,    0],
        [ 261,    0,    0, ...,    0,    0,    0]],

       ...,

       [[-459,    6,    

array([[[-468,   12,    0, ...,    0,    0,    0],
        [-495,   12,   -6, ...,    0,    0,    0],
        [-540,   12,    0, ...,    0,    0,    0],
        ...,
        [ 342,    0,    0, ...,    0,    0,    0],
        [ 369,   -6,  -18, ...,    0,    0,    0],
        [ 342,    6,    0, ...,    0,    0,    0]],

       [[-504,    6,    0, ...,    0,    0,    0],
        [-522,   12,    0, ...,    0,    0,    0],
        [-558,    6,    0, ...,    0,    0,    0],
        ...,
        [ 351,   -6,    0, ...,    0,    0,    0],
        [ 378,    0,  -12, ...,    0,    0,    0],
        [ 351,    6,    0, ...,    0,    0,    0]],

       [[-549,    6,    0, ...,    0,    0,    0],
        [-558,    6,    0, ...,    0,    0,    0],
        [-576,    6,    0, ...,    0,    0,    0],
        ...,
        [ 369,   -6,    0, ...,    0,    0,    0],
        [ 396,    0,  -12, ...,    0,    0,    0],
        [ 360,    6,    0, ...,    0,    0,    0]],

       ...,

       [[-594,    0,    

array([[[-603,    6,    0, ...,    0,    0,    0],
        [-603,    0,    0, ...,    0,    0,    0],
        [-594,   -6,    6, ...,    0,    0,    0],
        ...,
        [ 414,   -6,    0, ...,    0,    0,    0],
        [ 441,    0,  -12, ...,    0,    0,    0],
        [ 414,    6,    0, ...,    0,    0,    0]],

       [[-603,    0,    0, ...,    0,    0,    0],
        [-603,   -6,    0, ...,    0,    0,    0],
        [-603,    0,    0, ...,    0,    0,    0],
        ...,
        [ 414,  -12,    0, ...,    0,    0,    0],
        [ 450,    0,  -12, ...,    0,    0,    0],
        [ 414,    6,    0, ...,    0,    0,    0]],

       [[-612,    0,    0, ...,    0,    0,    0],
        [-612,   -6,    0, ...,    0,    0,    0],
        [-594,   -6,    0, ...,    0,    0,    0],
        ...,
        [ 423,   -6,    0, ...,    0,    0,    0],
        [ 450,    0,   -6, ...,    0,    0,    0],
        [ 423,    6,    0, ...,    0,    0,    0]],

       ...,

       [[-621,    0,    

array([[[-648,    0,    0, ...,    0,    0,    0],
        [-630,  -12,    0, ...,    0,    0,    0],
        [-621,    0,    0, ...,    0,    0,    0],
        ...,
        [ 405,  -12,    0, ...,    0,    0,    0],
        [ 432,    0,    0, ...,    0,    0,    0],
        [ 405,    6,    0, ...,    0,    0,    0]],

       [[-657,    0,    0, ...,    0,    0,    0],
        [-648,   -6,    0, ...,    0,    0,    0],
        [-630,    0,    0, ...,    0,    0,    0],
        ...,
        [ 387,   -6,    0, ...,    0,    0,    0],
        [ 423,    0,  -12, ...,    0,    0,    0],
        [ 396,    6,    0, ...,    0,    0,    0]],

       [[-684,    0,    0, ...,    0,    0,    0],
        [-675,    0,    0, ...,    0,    0,    0],
        [-657,   -6,    0, ...,    0,    0,    0],
        ...,
        [ 360,   -6,    0, ...,    0,    0,    0],
        [ 396,    0,  -12, ...,    0,    0,    0],
        [ 369,    6,    0, ...,    0,    0,    0]],

       ...,

       [[ 504,   24,  -3

array([[[ 441,   96,  -30, ...,    0,    0,    0],
        [ 477,    0,    0, ...,    0,    0,    0],
        [ 468,   18,  -18, ...,    0,    0,    0],
        ...,
        [ 261,  -18,   84, ...,    0,    0,    0],
        [ 342,    0,    0, ...,    0,    0,    0],
        [ 324,   54,  -54, ...,    0,    0,    0]],

       [[ 423,   90,   24, ...,    0,    0,    0],
        [ 468,    0,   -6, ...,    0,    0,    0],
        [ 468,   12,  -12, ...,    0,    0,    0],
        ...,
        [ 252,   60,   90, ...,    0,    0,    0],
        [ 324,    0,    0, ...,    0,    0,    0],
        [ 315,   42,  -54, ...,    0,    0,    0]],

       [[ 414,   66,   66, ...,    0,    0,    0],
        [ 468,    0,    0, ...,    0,    0,    0],
        [ 468,   12,   -6, ...,    0,    0,    0],
        ...,
        [ 252,  108,    0, ...,    0,    0,    0],
        [ 306,    0,    0, ...,    0,    0,    0],
        [ 306,   24,  -48, ...,    0,    0,    0]],

       ...,

       [[ 369,  -36,   4

array([[[ 360,  -60,  -30, ...,    0,    0,    0],
        [ 396,   12,    0, ...,    0,    0,    0],
        [ 360,    6,    0, ...,    0,    0,    0],
        ...,
        [ 243,    0,    0, ...,    0,    0,    0],
        [ 252,    6,  -12, ...,    0,    0,    0],
        [-459, -216,  108, ...,    0,    0,    0]],

       [[ 351,  -66,  -54, ...,    0,    0,    0],
        [ 387,   12,    0, ...,    0,    0,    0],
        [ 351,   12,    0, ...,    0,    0,    0],
        ...,
        [ 171,   66,  -48, ...,    0,    0,    0],
        [-513,  174,   18, ...,    0,    0,    0],
        [-828,   24,    6, ...,    0,    0,    0]],

       [[ 351,  -60,  -54, ...,    0,    0,    0],
        [ 369,   12,    0, ...,    0,    0,    0],
        [ 342,    6,    0, ...,    0,    0,    0],
        ...,
        [  72,  168, -102, ...,    0,    0,    0],
        [-765,   72,   42, ...,    0,    0,    0],
        [-828,    0,   -6, ...,    0,    0,    0]],

       ...,

       [[ 351,    0,   -

array([[[ -36,    0,    0, ...,    0,    0,    0],
        [ -54,    6,    0, ...,    0,    0,    0],
        [ -63,    0,    0, ...,    0,    0,    0],
        ...,
        [ -27,   -6,    0, ...,    0,    0,    0],
        [  -9,   -6,    0, ...,    0,    0,    0],
        [  18,   -6,    0, ...,    0,    0,    0]],

       [[ -63,    0,    0, ...,    0,    0,    0],
        [ -63,    0,    0, ...,    0,    0,    0],
        [ -54,    0,    0, ...,    0,    0,    0],
        ...,
        [ -27,   -6,    0, ...,    0,    0,    0],
        [  -9,   -6,    0, ...,    0,    0,    0],
        [   9,  -12,    0, ...,    0,    0,    0]],

       [[ -81,   12,    0, ...,    0,    0,    0],
        [-117,    6,    0, ...,    0,    0,    0],
        [-144,    6,    0, ...,    0,    0,    0],
        ...,
        [ -81,   -6,    0, ...,    0,    0,    0],
        [ -54,   -6,    0, ...,    0,    0,    0],
        [ -18,   -6,    0, ...,    0,    0,    0]],

       ...,

       [[ 153,    0,    

array([[[ 225,    0,    0, ...,    0,    0,    0],
        [ 180,   48,  -24, ...,    0,    0,    0],
        [-693,  150,  144, ...,    0,    0,    0],
        ...,
        [-495,  354,  108, ...,    0,    0,    0],
        [-846,    0,    0, ...,    0,    0,    0],
        [-837,   -6,    0, ...,    0,    0,    0]],

       [[ 243,    0,    0, ...,    0,    0,    0],
        [ 198,   48,  -24, ...,    0,    0,    0],
        [-693,  144,  138, ...,    0,    0,    0],
        ...,
        [-315,  510,  150, ...,    0,    0,    0],
        [-828,   -6,    0, ...,    0,    0,    0],
        [-819,  -12,    0, ...,    0,    0,    0]],

       [[ 252,    0,    0, ...,    0,    0,    0],
        [ 207,   48,  -24, ...,    0,    0,    0],
        [-693,  126,  126, ...,    0,    0,    0],
        ...,
        [-297,  510,  150, ...,    0,    0,    0],
        [-801,   -6,    6, ...,    0,    0,    0],
        [-774,  -18,    0, ...,    0,    0,    0]],

       ...,

       [[ 288,    0,    

array([[[ 315,    6,    0, ...,    0,    0,    0],
        [ 270,   48,  -30, ...,    0,    0,    0],
        [-783,   48,   36, ...,    0,    0,    0],
        ...,
        [-774,   24,   12, ...,    0,    0,    0],
        [-792,  -18,    6, ...,    0,    0,    0],
        [-441, -138,  -72, ...,    0,    0,    0]],

       [[ 324,    6,    0, ...,    0,    0,    0],
        [ 288,   36,  -24, ...,    0,    0,    0],
        [-756,   72,   54, ...,    0,    0,    0],
        ...,
        [-747,    6,    0, ...,    0,    0,    0],
        [-783,    0,    6, ...,    0,    0,    0],
        [  18, -294, -222, ...,    0,    0,    0]],

       [[ 333,    6,    0, ...,    0,    0,    0],
        [ 306,   36,  -24, ...,    0,    0,    0],
        [-747,   78,   60, ...,    0,    0,    0],
        ...,
        [-747,    0,    0, ...,    0,    0,    0],
        [-765,    0,    0, ...,    0,    0,    0],
        [  54, -288, -222, ...,    0,    0,    0]],

       ...,

       [[ 369,    6,    

array([[[ 387,    6,    0, ...,    0,    0,    0],
        [ 360,   30,  -18, ...,    0,    0,    0],
        [-729,   90,   72, ...,    0,    0,    0],
        ...,
        [-783,   -6,   -6, ...,    0,    0,    0],
        [-189,   30,  114, ...,    0,    0,    0],
        [ 171,  -54,  -42, ...,    0,    0,    0]],

       [[ 396,    0,    0, ...,    0,    0,    0],
        [ 369,   30,  -18, ...,    0,    0,    0],
        [-738,   78,   66, ...,    0,    0,    0],
        ...,
        [-792,    0,    0, ...,    0,    0,    0],
        [-360,   18,   84, ...,    0,    0,    0],
        [  81,  -84,  -78, ...,    0,    0,    0]],

       [[ 396,    6,    0, ...,    0,    0,    0],
        [ 369,   30,  -18, ...,    0,    0,    0],
        [-720,  102,   84, ...,    0,    0,    0],
        ...,
        [-756,   -6,   -6, ...,    0,    0,    0],
        [-549,   -6,   30, ...,    0,    0,    0],
        [ 144, -222, -162, ...,    0,    0,    0]],

       ...,

       [[ 405,    0,    

array([[[ 387,    0,    0, ...,    0,    0,    0],
        [ 342,   54,  -30, ...,    0,    0,    0],
        [-792,   24,   24, ...,    0,    0,    0],
        ...,
        [ 342,    0,    0, ...,    0,    0,    0],
        [ 288,  102,  -96, ...,    0,    0,    0],
        [-729,   48,   24, ...,    0,    0,    0]],

       [[ 378,    0,    0, ...,    0,    0,    0],
        [ 315,   84,  -48, ...,    0,    0,    0],
        [-738,  -78,   78, ...,    0,    0,    0],
        ...,
        [  -9,  192,   42, ...,    0,    0,    0],
        [-279,   54,   12, ...,    0,    0,    0],
        [-405,   12,   18, ...,    0,    0,    0]],

       [[ 369,   -6,    0, ...,    0,    0,    0],
        [ 288,  108,  -66, ...,    0,    0,    0],
        [-738,  -96,   90, ...,    0,    0,    0],
        ...,
        [ -18,   24,    0, ...,    0,    0,    0],
        [-234,    6,   18, ...,    0,    0,    0],
        [-135, -132,   42, ...,    0,    0,    0]],

       ...,

       [[ 360,  -30,   -

array([[[ 279,  -48,   -6, ...,    0,    0,    0],
        [ 207,  204, -150, ...,    0,    0,    0],
        [  72, -396, -234, ...,    0,    0,    0],
        ...,
        [ 414,    0,    0, ...,    0,    0,    0],
        [ 414,    0,    0, ...,    0,    0,    0],
        [ 414,    0,    0, ...,    0,    0,    0]],

       [[ 243,  -42,   -6, ...,    0,    0,    0],
        [ 180,  198, -150, ...,    0,    0,    0],
        [   0, -354, -210, ...,    0,    0,    0],
        ...,
        [ 405,    0,    0, ...,    0,    0,    0],
        [ 414,    0,    0, ...,    0,    0,    0],
        [ 414,    0,    0, ...,    0,    0,    0]],

       [[ 252,  -48,   -6, ...,    0,    0,    0],
        [ 180,  210, -156, ...,    0,    0,    0],
        [  99, -318, -258, ...,    0,    0,    0],
        ...,
        [ 306,    0,    0, ...,    0,    0,    0],
        [ 315,    6,   -6, ...,    0,    0,    0],
        [ 297,    0,    0, ...,    0,    0,    0]],

       ...,

       [[ 243,  -18,   -

array([[[-378,   72,    0, ...,    0,    0,    0],
        [-657,  114,  -18, ...,    0,    0,    0],
        [-864,  -18,   -6, ...,    0,    0,    0],
        ...,
        [-720,   36,    0, ...,    0,    0,    0],
        [-783,    6,    0, ...,    0,    0,    0],
        [-810,    0,    0, ...,    0,    0,    0]],

       [[-864,   18,  -12, ...,    0,    0,    0],
        [-909,  -12,    0, ...,    0,    0,    0],
        [-945,    0,    0, ...,    0,    0,    0],
        ...,
        [-765,  -90,  -42, ...,    0,    0,    0],
        [-783,   36,   18, ...,    0,    0,    0],
        [-828,    0,    0, ...,    0,    0,    0]],

       [[-666,  -54,    0, ...,    0,    0,    0],
        [-630,   54,  -12, ...,    0,    0,    0],
        [-837,   24,   12, ...,    0,    0,    0],
        ...,
        [-738,   42,  -72, ...,    0,    0,  -57],
        [-846,   -6,    0, ...,    0,    0,    0],
        [-846,    0,    0, ...,    0,    0,    0]],

       ...,

       [[-702,   -6,    

array([[[  36,    0,    0, ...,    0,    0,    0],
        [  63,  -12,    0, ...,    0,    0,    0],
        [  99,  -12,    0, ...,    0,    0,    0],
        ...,
        [ 207,   -6,    0, ...,    0,    0,    0],
        [ 234,   -6,    0, ...,    0,    0,    0],
        [ 252,   -6,    0, ...,    0,    0,    0]],

       [[  36,   -6,    0, ...,    0,    0,    0],
        [  72,  -12,    0, ...,    0,    0,    0],
        [ 117,  -18,    0, ...,    0,    0,    0],
        ...,
        [ 207,   -6,    0, ...,    0,    0,    0],
        [ 234,   -6,    0, ...,    0,    0,    0],
        [ 225,    6,    0, ...,    0,    0,    0]],

       [[   9,  -12,    0, ...,    0,    0,    0],
        [  36,   -6,    0, ...,    0,    0,    0],
        [  36,    6,    0, ...,    0,    0,    0],
        ...,
        [-261,   42,    0, ...,    0,    0,    0],
        [-432,   48,    0, ...,    0,    0,    0],
        [-558,   24,    0, ...,    0,    0,    0]],

       ...,

       [[-801,   -6,    

array([[[-621,   48,  -48, ...,    0,    0,    0],
        [-585, -192,  114, ...,    0,    0,    0],
        [  63,  -72,    6, ...,    0,    0,    0],
        ...,
        [1017,    0,    0, ...,    0,    0,    0],
        [1017,    0,    0, ...,    0,    0,    0],
        [1017,    0,    0, ...,    0,    0,    0]],

       [[-576,   48,  -54, ...,    0,    0,    0],
        [-558, -192,  120, ...,    0,    0,    0],
        [ 108,  -72,   12, ...,    0,    0,    0],
        ...,
        [1017,    0,    0, ...,    0,    0,    0],
        [1017,    0,    0, ...,    0,    0,    0],
        [1017,    0,    0, ...,    0,    0,    0]],

       [[-540,   42,  -60, ...,    0,    0,    0],
        [-495, -222,  120, ...,    0,    0,    0],
        [ 153,  -42,    6, ...,    0,    0,    0],
        ...,
        [1017,    0,    0, ...,    0,    0,    0],
        [1017,    0,    0, ...,    0,    0,    0],
        [1017,    0,    0, ...,    0,    0,    0]],

       ...,

       [[-531,    6,  -8

array([[[-279,  -12,    0, ...,    0,    0,    0],
        [-198,  -24,    0, ...,    0,    0,    0],
        [-108,  -30,    0, ...,    0,    0,    0],
        ...,
        [ 117,  -18,   -6, ...,    0,    0,    0],
        [ 171,  -30,   -6, ...,    0,    0,    0],
        [ 243,  -18,    6, ...,    0,    0,    0]],

       [[ 252,    0,    0, ...,    0,    0,    0],
        [ 261,  -12,    0, ...,    0,    0,    0],
        [ 288,   -6,    0, ...,    0,    0,    0],
        ...,
        [ 333,    0,    0, ...,    0,    0,    0],
        [ 333,    0,    0, ...,    0,    0,    0],
        [ 333,    0,    0, ...,    0,    0,    0]],

       [[  72,   90,   54, ...,    0,    0,    0],
        [  27,  -12,   -6, ...,    0,    0,    0],
        [  36,   -6,    0, ...,    0,    0,    0],
        ...,
        [ 288,   12,    6, ...,    0,    0,    0],
        [ 243,   18,    6, ...,    0,    0,    0],
        [ 207,    6,    6, ...,    0,    0,    0]],

       ...,

       [[-297,  378,  14

array([[[ -90,  216,   66, ...,    0,    0,    0],
        [-279,  -18,  -12, ...,    0,    0,    0],
        [-270,    6,   12, ...,    0,    0,    0],
        ...,
        [ -63,   -6,   18, ...,    0,    0,    0],
        [ -45,  -24,   12, ...,    0,    0,    0],
        [ -54,  -12,   18, ...,    0,    0,    0]],

       [[ 126,   12,    0, ...,    0,    0,    0],
        [  99,    0,    6, ...,    0,    0,    0],
        [  99,    0,    0, ...,    0,    0,    0],
        ...,
        [ 108,    0,    0, ...,    0,    0,    0],
        [ 117,    0,    0, ...,    0,    0,    0],
        [ 117,    0,    0, ...,    0,    0,    0]],

       [[ 288,   24,    0, ...,    0,    0,    0],
        [ 225,    6,    0, ...,    0,    0,    0],
        [ 216,    0,    0, ...,    0,    0,    0],
        ...,
        [ 216,    0,    0, ...,    0,    0,    0],
        [ 216,   -6,    0, ...,    0,    0,    0],
        [ 225,    0,    0, ...,    0,    0,    0]],

       ...,

       [[ 360,   -6,    

array([[[-774,   18,   12, ...,    0,    0,    0],
        [-792,    6,   24, ...,    0,    0,    0],
        [-126, -120,  -42, ...,    0,    0,    0],
        ...,
        [ 297,   -6,    0, ...,    0,    0,    0],
        [ 315,    0,    0, ...,    0,    0,    0],
        [ 315,   -6,    0, ...,    0,    0,    0]],

       [[-360,   18,   12, ...,    0,    0,    0],
        [-360,  -18,   12, ...,    0,    0,    0],
        [ 126, -156,  -96, ...,    0,    0,    0],
        ...,
        [ 234,   66,   12, ...,    0,    0,    0],
        [ 144,    6,    0, ...,    0,    0,    0],
        [ 108,   18,   -6, ...,    0,    0,    0]],

       [[ 135,  -30,    0, ...,    0,    0,    0],
        [ 189,  -18,    6, ...,    0,    0,    0],
        [ 225,    0,    6, ...,    0,    0,    0],
        ...,
        [-495,   60,   12, ...,    0,    0,    0],
        [-612,   24,   -6, ...,    0,    0,    0],
        [-693,    6,    6, ...,    0,    0,    0]],

       ...,

       [[ 225,   -6,    

array([[[ 405,    0,   18, ...,    0,    0,    0],
        [ 405,   -6,  -12, ...,    0,    0,    0],
        [-684,  180,  156, ...,    0,    0,    0],
        ...,
        [-612,    6,  -18, ...,    0,    0,    0],
        [-180, -204, -300, ...,    0,    0,    0],
        [  45, -132,   -6, ...,    0,    0,    0]],

       [[ 396,   -6,   18, ...,    0,    0,    0],
        [ 396,    0,   -6, ...,    0,    0,    0],
        [-666,  162,  138, ...,    0,    0,    0],
        ...,
        [-207,   84,   48, ...,    0,    0,    0],
        [ 243, -378,  -72, ...,    0,    0,    0],
        [ 630,    0,    0, ...,    0,    0,    0]],

       [[ 342,  -48,    0, ...,    0,    0,    0],
        [ 405,   12,  -12, ...,    0,    0,    0],
        [-666,  132,  126, ...,    0,    0,    0],
        ...,
        [-198,  114,   60, ...,    0,    0,    0],
        [ 315, -330,  -78, ...,    0,    0,    0],
        [ 648,    0,    0, ...,    0,    0,    0]],

       ...,

       [[ -36,   48,   -

array([[[-810,    0,    0, ...,    0,    0,    0],
        [-810,    0,    0, ...,    0,    0,    0],
        [-810,    0,    0, ...,    0,    0,    0],
        ...,
        [-747,   12,  -18, ...,    0,    0,    0],
        [-846,   18,    0, ...,    0,    0,    0],
        [-756, -114,    6, ...,    0,    0,    0]],

       [[-828,    0,    0, ...,    0,    0,    0],
        [-828,    0,    0, ...,    0,    0,    0],
        [-828,    0,    0, ...,    0,    0,    0],
        ...,
        [-765,  -30,   18, ...,    0,    0,    0],
        [-531,  -60,  -84, ...,    0,    0,    0],
        [-522,    0,    0, ...,    0,    0,    0]],

       [[-846,    0,    0, ...,    0,    0,    0],
        [-828,   -6,    0, ...,    0,    0,    0],
        [-819,    0,    0, ...,    0,    0,    0],
        ...,
        [-828,   -6,   -6, ...,    0,    0,    0],
        [-675,  -48,   60, ...,    0,    0,    0],
        [-333,  -90,  -96, ...,    0,    0,    0]],

       ...,

       [[-828,    6,  -1

array([[[ 270,    0,    0, ...,    0,    0,    0],
        [ 279,   -6,    0, ...,    0,    0,    0],
        [ 288,    0,    0, ...,    0,    0,    0],
        ...,
        [ 216,   12,    0, ...,    0,    0,    0],
        [ 144,   30,   -6, ...,    0,    0,    0],
        [  27,   42,   -6, ...,    0,    0,    0]],

       [[ 189,   18,    0, ...,    0,    0,    0],
        [  99,   30,   -6, ...,    0,    0,    0],
        [ -72,   54,    0, ...,    0,    0,    0],
        ...,
        [-549,   36,    0, ...,    0,    0,    0],
        [-657,   24,    6, ...,    0,    0,    0],
        [-729,   12,    6, ...,    0,    0,    0]],

       [[-648,   24,    0, ...,    0,    0,    0],
        [-729,   18,    6, ...,    0,    0,    0],
        [-738,   -6,    0, ...,    0,    0,    0],
        ...,
        [-648,   -6,    0, ...,    0,    0,    0],
        [-621,   -6,    0, ...,    0,    0,    0],
        [-594,   -6,    0, ...,    0,    0,    0]],

       ...,

       [[-243,   -6,    

array([[[1017,    0,    0, ...,    0,    0,    0],
        [1017,    0,    0, ...,    0,    0,    0],
        [1017,    0,    0, ...,    0,    0,    0],
        ...,
        [1017,    0,    0, ...,    0,    0,    0],
        [1017,    0,    0, ...,    0,    0,    0],
        [1017,    0,    0, ...,    0,    0,    0]],

       [[1017,    0,    0, ...,    0,    0,    0],
        [1017,    0,    0, ...,    0,    0,    0],
        [1017,    0,    0, ...,    0,    0,    0],
        ...,
        [1017,    0,    0, ...,    0,    0,    0],
        [1017,    0,    0, ...,    0,    0,    0],
        [1017,    0,    0, ...,    0,    0,    0]],

       [[1017,    0,    0, ...,    0,    0,    0],
        [1017,    0,    0, ...,    0,    0,    0],
        [1017,    0,    0, ...,    0,    0,    0],
        ...,
        [1017,    0,    0, ...,    0,    0,    0],
        [1017,    0,    0, ...,    0,    0,    0],
        [1017,    0,    0, ...,    0,    0,    0]],

       ...,

       [[ 693,   24,   -

array([[[ 306,  -12,    0, ...,    0,    0,    0],
        [ 342,   -6,    0, ...,    0,    0,    0],
        [ 342,    6,    0, ...,    0,    0,    0],
        ...,
        [ 369,   -6,    0, ...,    0,    0,    0],
        [ 369,    0,    0, ...,    0,    0,    0],
        [ 369,    0,    0, ...,    0,    0,    0]],

       [[ 333,    0,    0, ...,    0,    0,    0],
        [ 333,    0,    0, ...,    0,    0,    0],
        [ 342,    0,    0, ...,    0,    0,    0],
        ...,
        [ 369,    0,    0, ...,    0,    0,    0],
        [ 369,    0,    0, ...,    0,    0,    0],
        [ 360,    0,    0, ...,    0,    0,    0]],

       [[ 207,    0,   -6, ...,    0,    0,    0],
        [ 171,   30,  -18, ...,    0,    0,    0],
        [  90,   -6,   24, ...,    0,    0,    0],
        ...,
        [ 297,  -66,  -12, ...,    0,    0,    0],
        [ 360,    0,    0, ...,    0,    0,    0],
        [ 360,    0,    0, ...,    0,    0,    0]],

       ...,

       [[-333,  -30,  -5

array([[[ -54,   -6,  -18, ...,    0,    0,    0],
        [-108,  -12,    0, ...,    0,    0,    0],
        [ -72,  -60,    0, ...,    0,    0,    0],
        ...,
        [  27,  -78,   60, ...,    0,    0,    0],
        [  27,   30,    0, ...,    0,    0,    0],
        [ -18,  138,   -6, ...,    0,    0,    0]],

       [[ 117,    0,    0, ...,    0,    0,    0],
        [ 117,    6,    0, ...,    0,    0,    0],
        [ 117,    0,    0, ...,    0,    0,    0],
        ...,
        [ 126,    0,    0, ...,    0,    0,    0],
        [ 135,    6,    0, ...,    0,    0,    0],
        [ 117,    0,    0, ...,    0,    0,    0]],

       [[ 234,   -6,    0, ...,    0,    0,    0],
        [ 243,    0,    0, ...,    0,    0,    0],
        [ 243,    0,    0, ...,    0,    0,    0],
        ...,
        [ 243,    0,    0, ...,    0,    0,    0],
        [ 243,    0,    0, ...,    0,    0,    0],
        [ 234,    0,    0, ...,    0,    0,    0]],

       ...,

       [[ 369,    0,    

array([[[ 333,   -6,    0, ...,    0,    0,    0],
        [ 351,   -6,    0, ...,    0,    0,    0],
        [ 360,    0,    0, ...,    0,    0,    0],
        ...,
        [ 369,    0,    0, ...,    0,    0,    0],
        [ 369,    0,    0, ...,    0,    0,    0],
        [ 369,    0,    0, ...,    0,    0,    0]],

       [[   9,   24,    0, ...,    0,    0,    0],
        [ 198, -156,  -54, ...,    0,    0,    0],
        [ 351,    0,    0, ...,    0,    0,    0],
        ...,
        [ 369,    0,    0, ...,    0,    0,    0],
        [ 360,    0,    0, ...,    0,    0,    0],
        [ 369,    0,    0, ...,    0,    0,    0]],

       [[-612,  -42,    6, ...,    0,    0,    0],
        [  90, -264, -150, ...,    0,    0,    0],
        [ 333,    0,    0, ...,    0,    0,    0],
        ...,
        [ 369,    0,    0, ...,    0,    0,    0],
        [ 369,    0,    0, ...,    0,    0,    0],
        [ 369,    0,    0, ...,    0,    0,    0]],

       ...,

       [[  81,  -36,  -3

array([[[-108,   66,   24, ...,    0,    0,    0],
        [-162,   -6,   12, ...,    0,    0,    0],
        [ -72, -102,   66, ...,    0,    0,    0],
        ...,
        [-819,    0,    0, ...,    0,    0,    0],
        [-819,    0,    0, ...,    0,    0,    0],
        [-828,    0,    0, ...,    0,    0,    0]],

       [[ 603,   36,  -30, ...,    0,    0,    0],
        [ 612,    6,    0, ...,    0,    0,    0],
        [ 387,  180,   18, ...,    0,    0,    0],
        ...,
        [-810,    0,    0, ...,    0,    0,    0],
        [-810,    0,    0, ...,    0,    0,    0],
        [-819,    0,    0, ...,    0,    0,    0]],

       [[ 630,   12,   -6, ...,    0,    0,    0],
        [ 639,    0,    0, ...,    0,    0,    0],
        [ 306,  318,  -60, ...,    0,    0,    0],
        ...,
        [-801,    0,    0, ...,    0,    0,    0],
        [-810,    0,    0, ...,    0,    0,    0],
        [-810,    0,    0, ...,    0,    0,    0]],

       ...,

       [[ 639,  -18,  -2

array([[[-594,  -36,    6, ...,    0,    0,    0],
        [-405,  -60,    6, ...,    0,    0,    0],
        [-216,  -30,    0, ...,    0,    0,    0],
        ...,
        [ 162,    0,    0, ...,    0,    0,    0],
        [ 153,    0,    6, ...,    0,    0,    0],
        [ 153,    6,    0, ...,    0,    0,    0]],

       [[-513,   30,    6, ...,    0,    0,    0],
        [-603,   36,   -6, ...,    0,    0,    0],
        [-720,   42,   -6, ...,    0,    0,    0],
        ...,
        [-720,  -96,   18, ...,    0,    0,    0],
        [-333,  -66,  -12, ...,    0,    0,    0],
        [ -81,  -18,  -18, ...,    0,    0,    0]],

       [[-198,  -84,  -36, ...,    0,    0,    0],
        [-153,  -24,    0, ...,    0,    0,    0],
        [-252,  126,  -96, ...,    0,    0,    0],
        ...,
        [-387,  -48,   12, ...,    0,    0,    0],
        [-189,  -30,  -12, ...,    0,    0,    0],
        [-153,    0,    6, ...,    0,    0,    0]],

       ...,

       [[ 180,  -12,    

array([[[-144,   48,    6, ...,    0,    0,    0],
        [-306,   48,    0, ...,    0,    0,    0],
        [-486,   48,    0, ...,    0,    0,    0],
        ...,
        [-756,    0,    0, ...,    0,    0,    0],
        [-756,    0,    0, ...,    0,    0,    0],
        [-765,    0,    0, ...,    0,    0,    0]],

       [[-729,    0,    0, ...,    0,    0,    0],
        [-720,    0,    0, ...,    0,    0,    0],
        [-702,   -6,    0, ...,    0,    0,    0],
        ...,
        [-630,   -6,    0, ...,    0,    0,    0],
        [-612,   -6,    0, ...,    0,    0,    0],
        [-594,    0,    0, ...,    0,    0,    0]],

       [[-567,   -6,    0, ...,    0,    0,    0],
        [-549,    0,    0, ...,    0,    0,    0],
        [-558,    6,    0, ...,    0,    0,    0],
        ...,
        [-486,   -6,    0, ...,    0,    0,    0],
        [-450,  -12,    0, ...,    0,    0,    0],
        [-414,   -6,    0, ...,    0,    0,    0]],

       ...,

       [[ 504,  -42,    

array([[[1017,    0,    0, ...,    0,    0,    0],
        [1017,    0,    0, ...,    0,    0,    0],
        [1017,    0,    0, ...,    0,    0,    0],
        ...,
        [1017,    0,    0, ...,    0,    0,    0],
        [1017,    0,    0, ...,    0,    0,    0],
        [1017,    0,    0, ...,    0,    0,    0]],

       [[1017,    0,    0, ...,    0,    0,    0],
        [1017,    0,    0, ...,    0,    0,    0],
        [1017,    0,    0, ...,    0,    0,    0],
        ...,
        [1017,    0,    0, ...,    0,    0,    0],
        [1017,    0,    0, ...,    0,    0,    0],
        [1017,    0,    0, ...,    0,    0,    0]],

       [[1017,    0,    0, ...,    0,    0,    0],
        [1017,    0,    0, ...,    0,    0,    0],
        [1017,    0,    0, ...,    0,    0,    0],
        ...,
        [1017,    0,    0, ...,    0,    0,    0],
        [1017,    0,    0, ...,    0,    0,    0],
        [1017,    0,    0, ...,    0,    0,    0]],

       ...,

       [[  72,   24,    

array([[[ 360,    0,    0, ...,    0,    0,    0],
        [ 360,    0,    0, ...,    0,    0,    0],
        [ 360,    0,    0, ...,    0,    0,    0],
        ...,
        [ 342,    0,    0, ...,    0,    0,    0],
        [ 333,    0,    0, ...,    0,    0,    0],
        [ 324,    0,    0, ...,    0,    0,    0]],

       [[ 360,    0,    0, ...,    0,    0,    0],
        [ 351,    0,    0, ...,    0,    0,    0],
        [ 342,    0,    0, ...,    0,    0,    0],
        ...,
        [ 315,    0,    0, ...,    0,    0,    0],
        [ 324,    0,    0, ...,    0,    0,    0],
        [ 315,    0,    0, ...,    0,    0,    0]],

       [[ 351,    0,    0, ...,    0,    0,    0],
        [ 342,    0,    0, ...,    0,    0,    0],
        [ 333,    0,    0, ...,    0,    0,    0],
        ...,
        [ 297,    0,    0, ...,    0,    0,    0],
        [ 306,    0,    0, ...,    0,    0,    0],
        [ 315,    0,    0, ...,    0,    0,    0]],

       ...,

       [[-342,    6,  41

array([[[-162,   -6,    0, ...,    0,    0,    0],
        [-153,    6,    0, ...,    0,    0,    0],
        [-117,   -6,  -24, ...,    0,    0,    0],
        ...,
        [-135,   -6,    6, ...,    0,    0,    0],
        [-198,    6,   18, ...,    0,    0,    0],
        [ -81,  -90,   24, ...,    0,    0,    0]],

       [[ 117,    0,    0, ...,    0,    0,    0],
        [ 117,    6,    0, ...,    0,    0,    0],
        [  99,    0,    0, ...,    0,    0,    0],
        ...,
        [  54,    0,    0, ...,    0,    0,    0],
        [  -9,    0,   18, ...,    0,    0,    0],
        [  36,  -12,    0, ...,    0,    0,    0]],

       [[ 234,    0,    0, ...,    0,    0,    0],
        [ 216,    6,    0, ...,    0,    0,    0],
        [ 207,    0,    0, ...,    0,    0,    0],
        ...,
        [-135,   30,   -6, ...,    0,    0,    0],
        [  45, -126,  -12, ...,    0,    0,    0],
        [ 216,   -6,    0, ...,    0,    0,    0]],

       ...,

       [[ 360,    6,    

array([[[ 360,    6,    0, ...,    0,    0,    0],
        [ 342,    6,    0, ...,    0,    0,    0],
        [ 342,    0,    0, ...,    0,    0,    0],
        ...,
        [ 477,    6,  -24, ...,    0,    0,    0],
        [ 315,  126,    0, ...,    0,    0,    0],
        [ 234, -114,   54, ...,    0,    0,    0]],

       [[ 360,    6,    0, ...,    0,    0,    0],
        [ 342,    0,    0, ...,    0,    0,    0],
        [ 342,    0,    0, ...,    0,    0,    0],
        ...,
        [ 450,   24,  -12, ...,    0,    0,    0],
        [ 351,   54,  -30, ...,    0,    0,    0],
        [ 216,  -54,   30, ...,    0,    0,    0]],

       [[ 360,    0,    0, ...,    0,    0,    0],
        [ 342,    6,    0, ...,    0,    0,    0],
        [ 315,   12,  -12, ...,    0,    0,    0],
        ...,
        [   0,   -6,   -6, ...,    0,    0,    0],
        [ 135,  -42,  -36, ...,    0,    0,    0],
        [ 171,  -36,   12, ...,    0,    0,    0]],

       ...,

       [[ 261,   -6,    

array([[[-828,    0,    0, ...,    0,    0,    0],
        [-828,    0,    0, ...,    0,    0,    0],
        [-162, -126, -204, ...,    0,    0,    0],
        ...,
        [ 378,  -42, -102, ...,    0,    0,    0],
        [ 342,    6,  -12, ...,    0,    0,    0],
        [ 279,   18,   72, ...,    0,    0,    0]],

       [[-819,    0,    0, ...,    0,    0,    0],
        [-828,    0,    0, ...,    0,    0,    0],
        [-117,  -60,  -78, ...,    0,    0,    0],
        ...,
        [ 324,   12,  -24, ...,    0,    0,    0],
        [ 378,   48,   36, ...,    0,    0,    0],
        [ 225,   54,  114, ...,    0,    0,    0]],

       [[-819,    0,    0, ...,    0,    0,    0],
        [-819,    0,    0, ...,    0,    0,    0],
        [ -54,   24,   36, ...,    0,    0,    0],
        ...,
        [ 171,  -36,   54, ...,    0,    0,    0],
        [ 171,   48,  -78, ...,    0,    0,    0],
        [ -27,   66,  144, ...,    0,    0,    0]],

       ...,

       [[-144,  -18,   1

array([[[  45,   36,    0, ...,    0,    0,    0],
        [-117,   72,  -18, ...,    0,    0,    0],
        [-369,   30,    6, ...,    0,    0,    0],
        ...,
        [-513,  -42,   42, ...,    0,    0,    0],
        [-522,  -66,  -42, ...,    0,    0,    0],
        [-450,  -36,  -12, ...,    0,    0,    0]],

       [[-252,    6,    0, ...,    0,    0,    0],
        [-234,  -30,   12, ...,    0,    0,    0],
        [-153,    0,   -6, ...,    0,    0,    0],
        ...,
        [-261,   12,    0, ...,    0,    0,    0],
        [-270,    6,  -12, ...,    0,    0,    0],
        [-261,  -42,   18, ...,    0,    0,    0]],

       [[-135,  -12,    0, ...,    0,    0,    0],
        [ -99,   -6,    0, ...,    0,    0,    0],
        [ -72,    0,    0, ...,    0,    0,    0],
        ...,
        [-126,   -6,    6, ...,    0,    0,    0],
        [-126,   12,    0, ...,    0,    0,    0],
        [-144,   12,   -6, ...,    0,    0,    0]],

       ...,

       [[ -45,    6,    

array([[[-756,   -6,    0, ...,    0,    0,    0],
        [-738,    0,    0, ...,    0,    0,    0],
        [-729,    0,    0, ...,    0,    0,    0],
        ...,
        [-837,    6,    0, ...,    0,    0,    0],
        [-846,    0,   -6, ...,    0,    0,    0],
        [-855,    0,    0, ...,    0,    0,    0]],

       [[-603,    6,    0, ...,    0,    0,    0],
        [-630,    0,    0, ...,    0,    0,    0],
        [-621,   -6,    0, ...,    0,    0,    0],
        ...,
        [-783,    6,    0, ...,    0,    0,    0],
        [-810,    6,    0, ...,    0,    0,    0],
        [-819,    0,    0, ...,    0,    0,    0]],

       [[-378,  -12,    0, ...,    0,    0,    0],
        [-333,   -6,    0, ...,    0,    0,    0],
        [-324,    0,    0, ...,    0,    0,    0],
        ...,
        [-729,   12,    6, ...,    0,    0,    0],
        [-774,   12,    0, ...,    0,    0,    0],
        [-792,    6,    0, ...,    0,    0,    0]],

       ...,

       [[1017,    0,    

array([[[1017,    0,    0, ...,    0,    0,    0],
        [1017,    0,    0, ...,    0,    0,    0],
        [1017,    0,    0, ...,    0,    0,    0],
        ...,
        [-468,   48,    0, ...,    0,    0,    0],
        [-603,   24,    6, ...,    0,    0,    0],
        [-666,   12,   12, ...,    0,    0,    0]],

       [[1017,    0,    0, ...,    0,    0,    0],
        [1017,    0,    0, ...,    0,    0,    0],
        [1017,    0,    0, ...,    0,    0,    0],
        ...,
        [-504,   48,    6, ...,    0,    0,    0],
        [-621,   18,    6, ...,    0,    0,    0],
        [-666,   18,   12, ...,    0,    0,    0]],

       [[1017,    0,    0, ...,    0,    0,    0],
        [1017,    0,    0, ...,    0,    0,    0],
        [1008,    0,    0, ...,    0,    0,    0],
        ...,
        [-567,   42,    0, ...,    0,    0,    0],
        [-657,   12,    6, ...,    0,    0,    0],
        [-675,    6,    6, ...,    0,    0,    0]],

       ...,

       [[-117,    6,    

array([[[315,   6,   0, ...,   0,   0,   0],
        [306,   0,   0, ...,   0,   0,   0],
        [297,   6,   0, ...,   0,   0,   0],
        ...,
        [279,   0,   0, ...,   0,   0,   0],
        [279,   0,   0, ...,   0,   0,   0],
        [279,   0,   0, ...,   0,   0,   0]],

       [[315,   0,   0, ...,   0,   0,   0],
        [315,   0,   0, ...,   0,   0,   0],
        [306,   0,   0, ...,   0,   0,   0],
        ...,
        [297,   0,   0, ...,   0,   0,   0],
        [297,   0,   0, ...,   0,   0,   0],
        [288,   6,   0, ...,   0,   0,   0]],

       [[315,   0,   0, ...,   0,   0,   0],
        [315,   0,   0, ...,   0,   0,   0],
        [315,   0,   0, ...,   0,   0,   0],
        ...,
        [306,   0,   0, ...,   0,   0,   0],
        [306,   0,   0, ...,   0,   0,   0],
        [297,   6,   0, ...,   0,   0,   0]],

       ...,

       [[315,   0,   0, ...,   0,   0,   0],
        [324,   0,   0, ...,   0,   0,   0],
        [324,   0,   0, ...,   0,   0,   0

array([[[ 72, -30,  24, ...,   0,   0,   0],
        [387,  12,   0, ...,   0,   0,   0],
        [369,   0,   0, ...,   0,   0,   0],
        ...,
        [342,   0,   0, ...,   0,   0,   0],
        [333,   0,   0, ...,   0,   0,   0],
        [324,   0,   0, ...,   0,   0,   0]],

       [[126, -48,  24, ...,   0,   0,   0],
        [387,   6,   0, ...,   0,   0,   0],
        [369,   0,   0, ...,   0,   0,   0],
        ...,
        [351,   0,   0, ...,   0,   0,   0],
        [342,   0,   0, ...,   0,   0,   0],
        [324,   0,   0, ...,   0,   0,   0]],

       [[270, -36,  12, ...,   0,   0,   0],
        [360,   0,   0, ...,   0,   0,   0],
        [369,   0,   0, ...,   0,   0,   0],
        ...,
        [351,   0,   0, ...,   0,   0,   0],
        [342,   6,   0, ...,   0,   0,   0],
        [315,   0,   0, ...,   0,   0,   0]],

       ...,

       [[333, -24, -12, ...,   0,   0,   0],
        [369,   0,   0, ...,   0,   0,   0],
        [369,   0,   0, ...,   0,   0,   0

array([[[ 333,   96,   54, ...,    0,    0,    0],
        [ 360,  -12,   -6, ...,    0,    0,    0],
        [ 369,    0,    0, ...,    0,    0,    0],
        ...,
        [ 342,    6,    0, ...,    0,    0,    0],
        [ 324,    0,    0, ...,    0,    0,    0],
        [ 315,    0,    0, ...,    0,    0,    0]],

       [[ 378,  114,  -24, ...,    0,    0,    0],
        [ 342,  -24,  -12, ...,    0,    0,    0],
        [ 360,    0,    0, ...,    0,    0,    0],
        ...,
        [ 324,    0,    0, ...,    0,    0,    0],
        [ 315,    0,    0, ...,    0,    0,    0],
        [ 306,    6,    0, ...,    0,    0,    0]],

       [[ 342,   66,  -78, ...,    0,    0,    0],
        [ 306,  -48,  -12, ...,    0,    0,    0],
        [ 351,    0,    0, ...,    0,    0,    0],
        ...,
        [-225,  -12,    0, ...,    0,    0,    0],
        [-180,  -12,    0, ...,    0,    0,    0],
        [-126,  -12,    0, ...,    0,    0,    0]],

       ...,

       [[ 117,   54,  -9

array([[[ 297,   96, -114, ...,    0,    0,    0],
        [ 144,  -60,    0, ...,    0,    0,    0],
        [-774,  204,  168, ...,    0,    0,    0],
        ...,
        [-936,    0,    0, ...,    0,    0,    0],
        [-567, -258,  -18, ...,    0,    0,    0],
        [-342,   42,    6, ...,    0,    0,    0]],

       [[ 126,  168,   36, ...,    0,    0,    0],
        [ 108,  -66,    0, ...,    0,    0,    0],
        [-774,  186,  162, ...,    0,    0,    0],
        ...,
        [-900,    6,  -12, ...,    0,    0,    0],
        [-747,    6,    6, ...,    0,    0,    0],
        [-756,   42,   24, ...,    0,    0,    0]],

       [[  54,   60,  -42, ...,    0,    0,    0],
        [  72,  -72,    0, ...,    0,    0,    0],
        [-756,   48,   18, ...,    0,    0,    0],
        ...,
        [-900,   18,   18, ...,    0,    0,    0],
        [-126, -270, -144, ...,    0,    0,    0],
        [-801,    6,   18, ...,    0,    0,    0]],

       ...,

       [[-234,  -24,    

array([[[-684,   90,    0, ...,    0,    0,    0],
        [-738,  -12,  -36, ...,    0,    0,    0],
        [-441, -168,  -48, ...,    0,    0,    0],
        ...,
        [-252,  144,    0, ...,    0,    0,    0],
        [-423,   66,  -36, ...,    0,    0,    0],
        [-180,  -84,  -30, ...,    0,    0,    0]],

       [[-270,   36,   -6, ...,    0,    0,    0],
        [-342,    0,    0, ...,    0,    0,    0],
        [-369,   48,    0, ...,    0,    0,    0],
        ...,
        [-756,  -18,    6, ...,    0,    0,    0],
        [-711,    6,  -12, ...,    0,    0,    0],
        [-693,  -24,   12, ...,    0,    0,    0]],

       [[-207,   42,    6, ...,    0,    0,    0],
        [-279,   12,   -6, ...,    0,    0,    0],
        [-306,   12,    0, ...,    0,    0,    0],
        ...,
        [-414,   12,    0, ...,    0,    0,    0],
        [-459,   24,   -6, ...,    0,    0,    0],
        [-612,   84,   12, ...,    0,    0,    0]],

       ...,

       [[ -27,    6,    